### ISSUE TITLE
Where  app\build?

### ISSUE THREAD

**Issue by selevo** [mesarcik/REDTOOTH#1]
"Install the .apk file found in app/build/outputs/apk/ on any Android device using Andriod 5.0 or above."
Whare 'app/build/outputs/apk/ ' ?

**Comment by mesarcik** [comment]
Hi, you are correct it seems that the .apk is not in the specified directory. 

You will have to build the executable yourself.

**Comment by selevo** [comment]
Why didn’t you upload it here?
I think it would be convenient.
